import { MetricTile, StatusBadge, TraceDetails, TraceTable } from "@/components/demo-artifact-ui";
import { GitBranch, PageHeader, Panel, PanelTitle, StatusPill } from "@/components/workspace-shell";
import { getDemoWorkspace } from "@/lib/demo-workspace";

export default function TracePage() {
  const workspace = getDemoWorkspace();
  const traces = workspace.traces;
  const webTraces = traces.filter((trace) => trace.origin.surface === "web_chat").length;
  const evalTraces = traces.filter((trace) => trace.origin.surface === "eval").length;
  const failures = traces.filter((trace) => trace.status === "error").length;
  const totalLatency = traces.reduce((total, trace) => total + trace.latency_ms, 0);

  return (
    <>
      <PageHeader
        eyebrow="Trace inspection"
        title="Tool-call audit trail"
        description="Replay exported tool traces with provenance."
      />

      <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <MetricTile label="Tool calls" value={String(traces.length)} detail="Ordered trace model records" tone="accent" />
        <MetricTile label="Web traces" value={String(webTraces)} detail="Dashboard/report workflow calls" />
        <MetricTile label="Eval traces" value={String(evalTraces)} detail={workspace.eval_run.id} tone="success" />
        <MetricTile label="Total latency" value={`${totalLatency} ms`} detail={`${failures} recorded errors`} tone={failures ? "warning" : "success"} />
      </div>

      <Panel>
        <PanelTitle icon={GitBranch} title="Trace log" meta={workspace.trace_export.path} />
        <TraceTable traces={traces} />
        <div className="border-t border-border px-4 py-3">
          <StatusPill>Secrets redacted; token_id only is rendered when present</StatusPill>
        </div>
      </Panel>

      <div className="mt-4 grid gap-4 xl:grid-cols-[0.76fr_1.24fr]">
        <Panel>
          <PanelTitle icon={GitBranch} title="Provenance surfaces" />
          <div className="divide-y divide-border">
            {[
              ["web_chat", webTraces, "Generated by the demo web workflow with chat/session linkage."],
              ["eval", evalTraces, "Generated by deterministic smoke replay with eval_run_id linkage."],
            ].map(([surface, count, detail]) => (
              <div key={surface} className="px-4 py-4">
                <div className="flex items-center justify-between gap-3">
                  <span className="font-mono text-sm font-semibold">{surface}</span>
                  <StatusBadge tone="accent">{count} traces</StatusBadge>
                </div>
                <p className="mt-2 text-sm leading-6 text-muted">{detail}</p>
              </div>
            ))}
          </div>
        </Panel>

        <Panel>
          <PanelTitle icon={GitBranch} title="Expandable input/output" meta="trace detail" />
          <TraceDetails traces={traces} />
        </Panel>
      </div>
    </>
  );
}
