import { EmptyState, FileText, PageHeader, Panel, PanelTitle } from "@/components/workspace-shell";

export default function ReportPage() {
  return (
    <>
      <PageHeader
        eyebrow="Analysis report"
        title="Evidence-backed report draft"
        description="Report sections are reserved for real analysis outputs, claim-typed evidence, plots, and exported artifacts generated by the shared tool registry."
      />
      <div className="grid gap-4 lg:grid-cols-[1fr_24rem]">
        <Panel className="min-h-[34rem]">
          <PanelTitle icon={FileText} title="Findings" meta="empty" />
          <EmptyState>No biological findings or citations have been generated.</EmptyState>
        </Panel>
        <Panel>
          <PanelTitle icon={FileText} title="Evidence queue" />
          <EmptyState>Source-grounded evidence will be attached here before export.</EmptyState>
        </Panel>
      </div>
    </>
  );
}
